#!/usr/bin/env node
/**
 * Pure Node.js XLSX generator — no AI, no API key required.
 * Claude Code calls this after generating JSON outputs.
 *
 * Usage:
 *   node scripts/generate_xlsx.js brd     [outputDir] [clientSlug]
 *   node scripts/generate_xlsx.js sprint  [outputDir] [clientSlug]
 *   node scripts/generate_xlsx.js all     [outputDir] [clientSlug]
 *
 * Examples:
 *   node scripts/generate_xlsx.js brd "opportunities/Northwind Utilities" northwind
 *   node scripts/generate_xlsx.js all "opportunities/ACME Electronics"  acme
 *   node scripts/generate_xlsx.js all                                          (legacy: writes to outputs/)
 *
 * The BRD is produced by populating templates/brd_template.xlsx — the template
 * is the single source of truth for BRD column layout.
 */

const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

// argv[2] = command, argv[3] = outputDir, argv[4] = clientSlug
const RAW_OUTPUT_DIR = process.argv[3] || 'outputs';
const CLIENT_SLUG    = process.argv[4] || '';

// Resolve relative to the caller's current working directory (this script
// lives in the user-level presales-agent skill, not inside the client project)
const OUTPUTS = path.resolve(process.cwd(), RAW_OUTPUT_DIR);

// Build a prefixed filename: "northwind_brd.json" or "brd.json" if no slug
function fileName(base) {
  return CLIENT_SLUG ? `${CLIENT_SLUG}_${base}` : base;
}

// ─── BRD ──────────────────────────────────────────────────────────────────────
// The BRD is generated by POPULATING templates/brd_template.xlsx, never by
// rebuilding the sheet from scratch. Column order, headers, and merged header
// bands come from the template file itself, so editing the template changes
// the output without touching this script.

const TEMPLATE_PATH = path.join(__dirname, '..', 'templates', 'brd_template.xlsx');

// Row 2 = column group headers, row 3 = Simple/Medium/Complex tier headers,
// row 4 = first data row.
const HEADER_ROW = 2;
const TIER_ROW   = 3;
const FIRST_DATA_ROW = 4;

// Artifact buckets in template column order (K–BF), 3 columns each.
const ARTIFACT_KEYS = [
  'objects', 'objectAutomations', 'recordTypes', 'pageLayouts',
  'flows', 'triggers', 'apexClasses', 'lwc',
  'customUiUx', 'partnerApp', 'apis', 'batchExecution',
  'reports', 'dashboard', 'orgSetup', 'dataMigration',
];
const ARTIFACT_FIRST_COL = 'K';
const MISC_COL    = 'BG';
const EFFORT_COL  = 'BH';
const REVIEW_COL  = 'BI';

const EFFORT_BASIS_NOTE =
  'Effort basis: AI-assisted delivery — human review, validation, and UAT sign-off. ' +
  'Not full manual build effort. Per-item rate figures intentionally removed; ' +
  'see references/effort_estimation.md.';

function numberedList(value) {
  if (Array.isArray(value)) return value.map((a, i) => `${i + 1}. ${a}`).join('\n');
  return value || '';
}

// subBrn is already the fully-qualified decimal reference ("1.1" under BRN "1"),
// so it stands alone as the row's unique id — do not prefix it with brn again.
function rowRef(row) {
  if (row.subBrn != null && row.subBrn !== '') return String(row.subBrn);
  return String(row.brn || '');
}

function generateBrdXlsx() {
  const jsonPath = path.join(OUTPUTS, fileName('brd.json'));
  if (!fs.existsSync(jsonPath)) {
    console.error(`❌ ${jsonPath} not found. Claude must generate it first.`);
    process.exit(1);
  }
  if (!fs.existsSync(TEMPLATE_PATH)) {
    console.error(`❌ BRD template missing at ${TEMPLATE_PATH}. The skill install is incomplete.`);
    process.exit(1);
  }

  const rows = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

  // Load the template and verify it is the shape we expect before writing into
  // it — a silently reshaped template would produce a misaligned BRD.
  const wb = XLSX.readFile(TEMPLATE_PATH, { cellStyles: true });
  const sheetName = wb.SheetNames[0];
  const ws = wb.Sheets[sheetName];

  const expectHeaders = {
    A: 'Audit Comments', B: 'BRN', C: 'Module/Functional Area', D: 'Sub-Module',
    E: 'Phase', F: 'Description', G: 'Functional Assumptions',
    H: 'Technical Assumptions', I: 'Solution Approach', J: 'Imp Approach',
    [EFFORT_COL]: 'Efforts (Design, Build, UT)', [REVIEW_COL]: 'Review Comments',
  };
  for (const [col, expected] of Object.entries(expectHeaders)) {
    const cell = ws[col + HEADER_ROW];
    const actual = cell ? String(cell.v).trim() : '';
    if (actual !== expected) {
      console.error(`❌ Template mismatch at ${col}${HEADER_ROW}: expected "${expected}", found "${actual}".`);
      console.error('   templates/brd_template.xlsx has changed shape. Update ARTIFACT_KEYS/column');
      console.error('   constants in this script to match before generating.');
      process.exit(1);
    }
  }

  // Clear the printed per-item rate row (K1:BF1). Those rates describe a
  // manual-build estimating model that the effort figures below no longer use;
  // leaving them in place would make the sheet self-contradictory.
  const rateStart = XLSX.utils.decode_col(ARTIFACT_FIRST_COL);
  const rateEnd   = rateStart + ARTIFACT_KEYS.length * 3 - 1;
  for (let c = rateStart; c <= rateEnd; c++) delete ws[XLSX.utils.encode_col(c) + '1'];
  XLSX.utils.sheet_add_aoa(ws, [[EFFORT_BASIS_NOTE]], { origin: `${ARTIFACT_FIRST_COL}1` });

  // Build data rows in template column order.
  const data = rows.map((row) => {
    const counts = row.artifactCounts || {};
    const bucketValues = [];
    for (const key of ARTIFACT_KEYS) {
      const b = counts[key] || {};
      bucketValues.push(b.simple || 0, b.medium || 0, b.complex || 0);
    }
    return [
      row.auditComments || '',                                    // A
      rowRef(row),                                                // B
      row.module || '',                                           // C
      row.subModule || '',                                        // D
      row.phase || 'Phase 1',                                     // E
      row.description || '',                                      // F
      numberedList(row.functionalAssumptions),                    // G
      numberedList(row.technicalAssumptions),                     // H
      row.solutionApproach || '',                                 // I
      row.impApproach || '',                                      // J
      ...bucketValues,                                            // K–BF
      row.miscManualEfforts || 0,                                 // BG
      row.effortHours || 0,                                       // BH
      row.reviewComments || '',                                   // BI
    ];
  });

  XLSX.utils.sheet_add_aoa(ws, data, { origin: `A${FIRST_DATA_ROW}` });

  // Extend the sheet range to cover however many rows we wrote (the blank
  // template only declares 40).
  const lastRow = Math.max(FIRST_DATA_ROW + data.length - 1, TIER_ROW);
  ws['!ref'] = `A1:${REVIEW_COL}${lastRow}`;

  // Readable widths for the prose columns; artifact count columns stay narrow.
  ws['!cols'] = [
    { wch: 15 }, { wch: 9 }, { wch: 28 }, { wch: 32 }, { wch: 9 },
    { wch: 70 }, { wch: 80 }, { wch: 80 }, { wch: 60 }, { wch: 45 },
    ...Array.from({ length: ARTIFACT_KEYS.length * 3 }, () => ({ wch: 5 })),
    { wch: 12 }, { wch: 14 }, { wch: 24 },
  ];

  // ── Summary sheet ──
  const moduleMap = {};
  for (const row of rows) {
    if (!moduleMap[row.module]) moduleMap[row.module] = { effort: 0, misc: 0, count: 0 };
    moduleMap[row.module].effort += row.effortHours || 0;
    moduleMap[row.module].misc   += row.miscManualEfforts || 0;
    moduleMap[row.module].count  += 1;
  }
  const summaryData = [['Module', 'Phase', 'Row Count', 'Effort (h)', 'Misc Manual (h)', 'Total (h)']];
  for (const [mod, v] of Object.entries(moduleMap)) {
    const phase = rows.find((r) => r.module === mod)?.phase || 'Phase 1';
    summaryData.push([mod, phase, v.count, Math.round(v.effort), Math.round(v.misc), Math.round(v.effort + v.misc)]);
  }
  const grandEffort = rows.reduce((s, r) => s + (r.effortHours || 0), 0);
  const grandMisc   = rows.reduce((s, r) => s + (r.miscManualEfforts || 0), 0);
  summaryData.push(['GRAND TOTAL', '', rows.length, Math.round(grandEffort), Math.round(grandMisc), Math.round(grandEffort + grandMisc)]);

  // ── Open clarifications ──
  const clarifData = [['BRN', 'Sub-Module', 'Clarification']];
  for (const row of rows) {
    if (row.reviewComments) {
      clarifData.push([rowRef(row), row.subModule, row.reviewComments]);
    }
  }

  if (sheetName !== 'BRD') {
    wb.SheetNames[wb.SheetNames.indexOf(sheetName)] = 'BRD';
    wb.Sheets['BRD'] = ws;
    delete wb.Sheets[sheetName];
  }
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summaryData), 'Summary');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(clarifData), 'Open Clarifications');

  const outPath = path.join(OUTPUTS, fileName('brd.xlsx'));
  XLSX.writeFile(wb, outPath);
  console.log(`✅ ${fileName('brd.xlsx')} — ${rows.length} rows, ${Math.round(grandEffort + grandMisc)}h total (from template)`);
}

// ─── Sprint Plan ──────────────────────────────────────────────────────────────
function generateSprintXlsx() {
  const jsonPath = path.join(OUTPUTS, fileName('sprint_plan.json'));
  if (!fs.existsSync(jsonPath)) {
    console.error(`❌ ${jsonPath} not found. Claude must generate it first.`);
    process.exit(1);
  }

  const plan = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  const { parameters: p, moduleEfforts, weeklyGrid, roleHourSummary } = plan;

  const wb = XLSX.utils.book_new();

  // Sheet 1: Module Summary
  const modData = [['Module','Phase','Total Effort (h)','Data Load (h)','Dev Effort (h)']];
  for (const m of (moduleEfforts || [])) {
    modData.push([m.module, m.phase, m.totalEffort, m.dataLoadEffort, m.devEffort]);
  }
  if (p) {
    modData.push(['GRAND TOTAL','', p.totalGrandEffort, p.totalDataLoadEffort, p.totalDevEffort]);
  }
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(modData), 'Module Summary');

  // Sheet 2: Sprint Parameters
  if (p) {
    const paramData = [
      ['Parameter','Value'],
      ['Number of Developers', p.numberOfDevelopers],
      ['Dev Capacity per Sprint (h)', p.devCapacityPerSprint],
      ['Grand Total Effort (h)', p.totalGrandEffort],
      ['Data Load Effort (h)', p.totalDataLoadEffort],
      ['Dev Effort (excl. data load) (h)', p.totalDevEffort],
      ['Number of Sprints', p.numberOfSprints],
      ['Balance Effort (h)', p.balanceEffort],
      ['Pre-Sprint Weeks', p.preSprintWeeks],
      ['Post-Sprint Weeks', p.postSprintWeeks],
      ['Total Project Weeks', p.totalProjectWeeks],
      ['Total Project Duration (months)', +(p.totalProjectWeeks / 4.33).toFixed(1)],
    ];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(paramData), 'Sprint Parameters');
  }

  // Sheet 3: Sprint Grid
  if (weeklyGrid && weeklyGrid.length > 0) {
    const devCount = weeklyGrid[0]?.allocation?.developers?.length || 1;
    const gridHeaders = [
      'Week','Sprint','Phase','BA (h)','SA (h)',
      ...Array.from({length: devCount}, (_,i) => `TS-${i+1} (h)`),
      'DS (h)','QA (h)','Total (h)',
    ];
    const gridData = [gridHeaders];
    for (const w of weeklyGrid) {
      gridData.push([
        w.weekNumber, w.sprintNumber || '', w.phase,
        w.allocation.ba, w.allocation.sa,
        ...(w.allocation.developers || []),
        w.allocation.ds, w.allocation.qa,
        w.totalHours,
      ]);
    }
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(gridData), 'Sprint Grid');
  }

  // Sheet 4: Role Hours
  if (roleHourSummary) {
    const rh = roleHourSummary;
    const roleData = [
      ['Role','Total Hours'],
      ['Business Analyst (BA)', rh.ba],
      ['Solution Architect (SA)', rh.sa],
      ...(rh.developers || []).map(d => [d.name, d.hours]),
      ['Delivery Scrum (DS)', rh.ds],
      ['Quality Assurance (QA)', rh.qa],
      ['GRAND TOTAL', rh.grandTotal],
    ];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(roleData), 'Role Hours');
  }

  XLSX.writeFile(wb, path.join(OUTPUTS, fileName('sprint_plan.xlsx')));
  console.log(`✅ ${fileName('sprint_plan.xlsx')} — ${p?.numberOfSprints || '?'} sprints`);

  // Timeline sheet
  const timelinePath = path.join(OUTPUTS, fileName('timeline.json'));
  const wb2 = XLSX.utils.book_new();

  let timelineData;
  if (fs.existsSync(timelinePath)) {
    const tl = JSON.parse(fs.readFileSync(timelinePath, 'utf8'));
    timelineData = [
      ['#','Task Title','Owner','Start Week','End Week','Duration (wks)','Effort (h)','Phase'],
      ...(tl.phases || []).map(ph => [
        ph.serial, ph.taskTitle, ph.taskOwner,
        ph.startWeek, ph.endWeek, ph.endWeek - ph.startWeek + 1,
        ph.effortHours || '', ph.phase,
      ]),
      ['','TOTAL PROJECT','',' 1', tl.totalWeeks, tl.totalWeeks, p?.totalGrandEffort || '', ''],
    ];
  } else {
    // Minimal timeline from sprint parameters
    timelineData = [['Note'],['Run Claude to generate timeline.json for detailed view']];
  }

  XLSX.utils.book_append_sheet(wb2, XLSX.utils.aoa_to_sheet(timelineData), 'Timeline');
  XLSX.writeFile(wb2, path.join(OUTPUTS, fileName('timeline.xlsx')));
  console.log(`✅ ${fileName('timeline.xlsx')}`);
}

// ─── Entry point ─────────────────────────────────────────────────────────────
const cmd = process.argv[2] || 'all';

if (!fs.existsSync(OUTPUTS)) {
  fs.mkdirSync(OUTPUTS, { recursive: true });
}

switch (cmd) {
  case 'brd':
  case 'scope': // legacy alias — the scope matrix is now the BRD
    generateBrdXlsx();
    break;
  case 'sprint':
    generateSprintXlsx();
    break;
  case 'all':
    if (fs.existsSync(path.join(OUTPUTS, fileName('brd.json'))))         generateBrdXlsx();
    if (fs.existsSync(path.join(OUTPUTS, fileName('sprint_plan.json')))) generateSprintXlsx();
    break;
  default:
    console.error(`Unknown command: ${cmd}. Use: brd | sprint | all`);
    process.exit(1);
}
